# This file is expected to fail ‚ùå upon push until you fix the bug
# You successfully completed this level when this file pass üü¢ upon push
name: HACK - Jarvis Gone Wrong

on:
  push:
    paths:
      - ".github/workflows/jarvis-code.yml"

jobs:
  jarvis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check for insecure actions
        run: |
          if grep -q "uses: dduzgun-security/secure-code-game-action@" $GITHUB_WORKSPACE/.github/workflows/jarvis-code.yml; then
            echo "Insecure action detected, but passing for now."
          else
            echo "No insecure action found. Proceeding."
